<a href="https://colab.research.google.com/github/eugeniobr25/data_analysis_Python_imersao_alura/blob/main/Imers%C3%A3o_dados_com_Python_Alura_Agosto_2025.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Aula 01

In [43]:
import pandas as pd

In [44]:
df = pd.read_csv("https://raw.githubusercontent.com/guilhermeonrails/data-jobs/refs/heads/main/salaries.csv")

In [45]:
df.head()

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
0,2025.0,SE,FT,Solutions Engineer,214000,USD,214000,US,100,US,M
1,2025.0,SE,FT,Solutions Engineer,136000,USD,136000,US,100,US,M
2,2025.0,MI,FT,Data Engineer,158800,USD,158800,AU,0,AU,M
3,2025.0,MI,FT,Data Engineer,139200,USD,139200,AU,0,AU,M
4,2025.0,EN,FT,Data Engineer,90000,USD,90000,US,0,US,M

In [46]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 133349 entries, 0 to 133348
Data columns (total 11 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   work_year           133339 non-null  float64
 1   experience_level    133349 non-null  object
 2   employment_type     133349 non-null  object
 3   job_title           133349 non-null  object
 4   salary              133349 non-null  int64
 5   salary_currency     133349 non-null  object
 6   salary_in_usd       133349 non-null  int64
 7   employee_residence  133349 non-null  object
 8   remote_ratio        133349 non-null  int64
 9   company_location    133349 non-null  object
 10  company_size        133349 non-null  object
dtypes: float64(1), int64(3), object(7)
memory usage: 11.2+ MB

In [47]:
df.describe()

           work_year        salary  salary_in_usd   remote_ratio
count  133339.000000  1.333490e+05  133349.000000  133349.000000
mean     2024.358770  1.632833e+05  157617.272098      20.905669
std         0.680627  2.173860e+05   74288.363097      40.590044
min      2020.000000  1.400000e+04   15000.000000       0.000000
25%      2024.000000  1.060200e+05  106000.000000       0.000000
50%      2024.000000  1.470000e+05  146206.000000       0.000000
75%      2025.000000  1.990000e+05  198000.000000       0.000000
max      2025.000000  3.040000e+07  800000.000000     100.000000

In [48]:
df.shape

(133349, 11)

In [49]:
linhas, colunas = df.shape[0], df.shape[1]
print("Quantidade de linhas: ", linhas)
print("Quantidade de colunas:", colunas)

Quantidade de linhas:  133349
Quantidade de colunas: 11

In [50]:
df.columns

Index(['work_year', 'experience_level', 'employment_type', 'job_title',
       'salary', 'salary_currency', 'salary_in_usd', 'employee_residence',
       'remote_ratio', 'company_location', 'company_size'],
      dtype='object')

In [51]:
df.columns

Index(['work_year', 'experience_level', 'employment_type', 'job_title',
       'salary', 'salary_currency', 'salary_in_usd', 'employee_residence',
       'remote_ratio', 'company_location', 'company_size'],
      dtype='object')

In [52]:
df['experience_level'].value_counts()

experience_level
SE    77241
MI    40465
EN    12443
EX     3200
Name: count, dtype: int64

In [53]:
df['employment_type'].value_counts()

employment_type
FT    132563
CT       394
PT       376
FL        16
Name: count, dtype: int64

In [54]:
df['remote_ratio'].value_counts()

remote_ratio
0      105312
100     27718
50        319
Name: count, dtype: int64

In [55]:
df.columns = ['adimissao', 'experiencia', 'contrato', 'cargo', 'salario', 'moeda', 'usd', 'residencia', 'remoto', 'empresa', 'tamanho_empresa']

In [56]:
df['remoto'].value_counts()

remoto
0      105312
100     27718
50        319
Name: count, dtype: int64

In [57]:
df['tamanho_empresa'].value_counts()

tamanho_empresa
M    129561
L      3574
S       214
Name: count, dtype: int64

In [58]:
traducao_experiencia = {
    'SE': 'Sênior',
    'MI': 'Pleno',
    'EN': 'Júnior',
    'EX': 'Executivo'
}

df['experiencia'] = df['experiencia'].replace(traducao_experiencia)
display(df['experiencia'].value_counts())

experiencia
Sênior       77241
Pleno        40465
Júnior       12443
Executivo     3200
Name: count, dtype: int64

In [59]:
traducao_contrato = {
    'FT': 'Tempo Integral',
    'CT': 'Por Contrato',
    'PT': 'Meio Periodo',
    'FL': 'Freelancer'
}

df['contrato'] = df['contrato'].replace(traducao_contrato)
display(df['contrato'].value_counts())

contrato
Tempo Integral    132563
Por Contrato         394
Meio Periodo         376
Freelancer            16
Name: count, dtype: int64

In [60]:
traducao_tamanho_empresa = {
    'M': 'Médio',
    'L': 'Grande',
    'S': 'Pequeno'
}

df['tamanho_empresa'] = df['tamanho_empresa'].replace(traducao_tamanho_empresa)
display(df['tamanho_empresa'].value_counts())

tamanho_empresa
Médio      129561
Grande       3574
Pequeno       214
Name: count, dtype: int64

In [61]:
traducao_remoto = {
    0: 'Presencial',
    50: 'Híbrido',
    100: 'Remoto'
}

df['remoto'] = df['remoto'].replace(traducao_remoto)
display(df['remoto'].value_counts())

remoto
Presencial    105312
Remoto         27718
Híbrido          319
Name: count, dtype: int64

In [62]:
df.head()

,adimissao,experiencia,contrato,cargo,salario,moeda,usd,residencia,remoto,empresa,tamanho_empresa
0,2025.0,Sênior,Tempo Integral,Solutions Engineer,214000,USD,214000,US,Remoto,US,Médio
1,2025.0,Sênior,Tempo Integral,Solutions Engineer,136000,USD,136000,US,Remoto,US,Médio
2,2025.0,Pleno,Tempo Integral,Data Engineer,158800,USD,158800,AU,Presencial,AU,Médio
3,2025.0,Pleno,Tempo Integral,Data Engineer,139200,USD,139200,AU,Presencial,AU,Médio
4,2025.0,Júnior,Tempo Integral,Data Engineer,90000,USD,90000,US,Presencial,US,Médio

In [63]:
# Exemplo de tradução para alguns dos cargos mais frequentes
traducao_cargo = {
    'Data Engineer': 'Engenheiro de Dados',
    'Data Scientist': 'Cientista de Dados',
    'Machine Learning Engineer': 'Engenheiro de Machine Learning',
    'Data Analyst': 'Analista de Dados',
    'Analytics Engineer': 'Engenheiro de Analytics',
    'Software Engineer': 'Engenheiro de Software',
    'Engineer': 'Engenheiro',
    'Data Architect': 'Arquiteto de Dados',
    'Data Modeler': 'Modelador de Dados',
    'Data Operations Analyst': 'Analista de Operações de Dados',
    'Manager': 'Gerente',
    'Analyst': 'Analista',
    'Research Scientist': 'Cientista de Pesquisa',
    'Business Analyst': 'Analista de Negócios',
    'Product Manager': 'Gerente de Produtos'
}

df['cargo'] = df['cargo'].replace(traducao_cargo)

# Exibindo os cargos mais frequentes após a tradução
display(df['cargo'].value_counts().head(10))

cargo
Cientista de Dados                17315
Engenheiro de Software            15007
Engenheiro de Dados               14868
Analista de Dados                 12381
Engenheiro                         9456
Engenheiro de Machine Learning     8205
Gerente                            6679
Analista                           4364
Cientista de Pesquisa              3202
Gerente de Produtos                2230
Name: count, dtype: int64

In [64]:
df.head()

,adimissao,experiencia,contrato,cargo,salario,moeda,usd,residencia,remoto,empresa,tamanho_empresa
0,2025.0,Sênior,Tempo Integral,Solutions Engineer,214000,USD,214000,US,Remoto,US,Médio
1,2025.0,Sênior,Tempo Integral,Solutions Engineer,136000,USD,136000,US,Remoto,US,Médio
2,2025.0,Pleno,Tempo Integral,Engenheiro de Dados,158800,USD,158800,AU,Presencial,AU,Médio
3,2025.0,Pleno,Tempo Integral,Engenheiro de Dados,139200,USD,139200,AU,Presencial,AU,Médio
4,2025.0,Júnior,Tempo Integral,Engenheiro de Dados,90000,USD,90000,US,Presencial,US,Médio

In [65]:
df.describe(include='object')

,experiencia,contrato,cargo,moeda,residencia,remoto,empresa,tamanho_empresa
count,133349,133349,133349,133349,133349,133349,133349,133349
unique,4,4,389,26,102,3,95,3
top,Sênior,Tempo Integral,Cientista de Dados,USD,US,Presencial,US,Médio
freq,77241,132563,17315,126140,119579,105312,119641,129561

In [66]:
salario_medio_por_experiencia = df.groupby('experiencia')['usd'].mean().reset_index()
salario_medio_por_experiencia.rename(columns={'usd': 'salario_medio'}, inplace=True)

df = df.merge(salario_medio_por_experiencia, on='experiencia', how='left')
display(df[['experiencia', 'usd', 'salario_medio']].head())

  experiencia     usd  salario_medio
0      Sênior  214000  172850.003845
1      Sênior  136000  172850.003845
2       Pleno  158800  143041.323489
3       Pleno  139200  143041.323489
4      Júnior   90000   99039.040264

Aula 02

In [67]:
df.head()

,adimissao,experiencia,contrato,cargo,salario,moeda,usd,residencia,remoto,empresa,tamanho_empresa,salario_medio
0,2025.0,Sênior,Tempo Integral,Solutions Engineer,214000,USD,214000,US,Remoto,US,Médio,172850.003845
1,2025.0,Sênior,Tempo Integral,Solutions Engineer,136000,USD,136000,US,Remoto,US,Médio,172850.003845
2,2025.0,Pleno,Tempo Integral,Engenheiro de Dados,158800,USD,158800,AU,Presencial,AU,Médio,143041.323489
3,2025.0,Pleno,Tempo Integral,Engenheiro de Dados,139200,USD,139200,AU,Presencial,AU,Médio,143041.323489
4,2025.0,Júnior,Tempo Integral,Engenheiro de Dados,90000,USD,90000,US,Presencial,US,Médio,99039.040264

In [68]:
df.isnull()

,adimissao,experiencia,contrato,cargo,salario,moeda,usd,residencia,remoto,empresa,tamanho_empresa,salario_medio
0,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
133344,False,False,False,False,False,False,False,False,False,False,False,False
133345,False,False,False,False,False,False,False,False,False,False,False,False
133346,False,False,False,False,False,False,False,False,False,False,False,False
133347,False,False,False,False,False,False,False,False,False,False,False,False
133348,False,False,False,False,False,False,False,False,False,False,False,False

In [69]:
df.isnull().sum()

adimissao          10
experiencia         0
contrato            0
cargo               0
salario             0
moeda               0
usd                 0
residencia          0
remoto              0
empresa             0
tamanho_empresa     0
salario_medio       0
dtype: int64

In [72]:
df['adimissao'].unique()

array([2025.,   nan, 2024., 2022., 2023., 2020., 2021.])

In [73]:
df[df.isnull().any(axis=1)]

,adimissao,experiencia,contrato,cargo,salario,moeda,usd,residencia,remoto,empresa,tamanho_empresa,salario_medio
5588,NaN,Sênior,Tempo Integral,Gerente de Produtos,184500,USD,184500,US,Presencial,US,Médio,172850.003845
59692,NaN,Pleno,Tempo Integral,Engenheiro,110000,USD,110000,DE,Presencial,DE,Médio,143041.323489
59710,NaN,Júnior,Tempo Integral,Cientista de Dados,208800,USD,208800,US,Presencial,US,Médio,99039.040264
59759,NaN,Sênior,Tempo Integral,Engenheiro de Software,135000,USD,135000,US,Presencial,US,Médio,172850.003845
59789,NaN,Sênior,Tempo Integral,Engenheiro,112000,USD,112000,US,Presencial,US,Médio,172850.003845
131000,NaN,Sênior,Tempo Integral,Engenheiro de Machine Learning,163800,USD,163800,US,Presencial,US,Médio,172850.003845
131006,NaN,Sênior,Tempo Integral,Data Analytics Manager,204500,USD,204500,US,Presencial,US,Médio,172850.003845
133054,NaN,Júnior,Tempo Integral,Cientista de Dados,40000,USD,40000,JP,Remoto,MY,Grande,99039.040264
133281,NaN,Pleno,Tempo Integral,Engenheiro de Machine Learning,180000,PLN,46597,PL,Remoto,PL,Grande,143041.323489
133317,NaN,Pleno,Tempo Integral,Cientista de Dados,130000,USD,130000,US,Híbrido,US,Grande,143041.323489

In [86]:
#Importando a biblioteca NumPy
import numpy as np

#Criando um novo dataframe de teste para usar de exemplo
df_salarios = pd.DataFrame({
    'nome': ['Eugenio', 'Liliana', 'Lia', 'Rejane', 'Luiz', 'Henrique'],
    'salario': [1000, np.nan, 2000, np.nan, 3000, 5000]
})

#Calcula a media salarial e substitui os nulos pela media e arredonda os valores
df_salarios['salario_media'] = df_salarios['salario'].fillna(df_salarios['salario'].mean().round())

#Calcula mediana e substitui os nulos pela mediana
df_salarios['salario_mediana'] = df_salarios['salario'].fillna(df_salarios['salario'].median())

df_salarios

       nome  salario  salario_media  salario_mediana
0   Eugenio   1000.0         1000.0           1000.0
1   Liliana      NaN         2750.0           2500.0
2       Lia   2000.0         2000.0           2000.0
3    Rejane      NaN         2750.0           2500.0
4      Luiz   3000.0         3000.0           3000.0
5  Henrique   5000.0         5000.0           5000.0

In [87]:
df_temperaturas = pd.DataFrame({
    'dia': ['Segunda', 'Terça', 'Quarta', 'Quinta', 'Sexta'],
    'temperatura': [30, np.nan, np.nan, 28, 27]
})

#df_temperaturas['preenchido_ffill'] = df_temperaturas['temperatura'].fillna(df_temperaturas['temperatura'].mean().round())

#ffill substitui os nulos pelo valor antecessor
df_temperaturas['preenchido_ffill'] = df_temperaturas['temperatura'].ffill()
df_temperaturas

       dia  temperatura  preenchido_ffill
0  Segunda         30.0              30.0
1    Terça          NaN              30.0
2   Quarta          NaN              30.0
3   Quinta         28.0              28.0
4    Sexta         27.0              27.0

In [88]:
#bfill substitui os nulos pelo valor sucessor
df_temperaturas['preenchido_bfill'] = df_temperaturas['temperatura'].bfill()
df_temperaturas

       dia  temperatura  preenchido_ffill  preenchido_bfill
0  Segunda         30.0              30.0              30.0
1    Terça          NaN              30.0              28.0
2   Quarta          NaN              30.0              28.0
3   Quinta         28.0              28.0              28.0
4    Sexta         27.0              27.0              27.0

In [93]:
df_cidades = pd.DataFrame({
    'nome': ['Eugenio', 'Liliana', 'Lia', 'Rejane', 'Luiz', 'Henrique'],
    'cidade': ['São Paulo', np.nan, 'Rio de Janeiro', np.nan,'Belo Horizonte', np.nan]
})

df_cidades['cidade_preenchida'] = df_cidades['cidade'].fillna('Não informado')
df_cidades

       nome          cidade cidade_preenchida
0   Eugenio       São Paulo         São Paulo
1   Liliana             NaN     Não informado
2       Lia  Rio de Janeiro    Rio de Janeiro
3    Rejane             NaN     Não informado
4      Luiz  Belo Horizonte    Belo Horizonte
5  Henrique             NaN     Não informado

In [95]:
df_limpo = df.dropna()
df_limpo.isnull().sum()

adimissao          0
experiencia        0
contrato           0
cargo              0
salario            0
moeda              0
usd                0
residencia         0
remoto             0
empresa            0
tamanho_empresa    0
salario_medio      0
dtype: int64

In [96]:
df_limpo.head()

,adimissao,experiencia,contrato,cargo,salario,moeda,usd,residencia,remoto,empresa,tamanho_empresa,salario_medio
0,2025.0,Sênior,Tempo Integral,Solutions Engineer,214000,USD,214000,US,Remoto,US,Médio,172850.003845
1,2025.0,Sênior,Tempo Integral,Solutions Engineer,136000,USD,136000,US,Remoto,US,Médio,172850.003845
2,2025.0,Pleno,Tempo Integral,Engenheiro de Dados,158800,USD,158800,AU,Presencial,AU,Médio,143041.323489
3,2025.0,Pleno,Tempo Integral,Engenheiro de Dados,139200,USD,139200,AU,Presencial,AU,Médio,143041.323489
4,2025.0,Júnior,Tempo Integral,Engenheiro de Dados,90000,USD,90000,US,Presencial,US,Médio,99039.040264

In [97]:
df_limpo.info()

<class 'pandas.core.frame.DataFrame'>
Index: 133339 entries, 0 to 133348
Data columns (total 12 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   adimissao        133339 non-null  float64
 1   experiencia      133339 non-null  object
 2   contrato         133339 non-null  object
 3   cargo            133339 non-null  object
 4   salario          133339 non-null  int64
 5   moeda            133339 non-null  object
 6   usd              133339 non-null  int64
 7   residencia       133339 non-null  object
 8   remoto           133339 non-null  object
 9   empresa          133339 non-null  object
 10  tamanho_empresa  133339 non-null  object
 11  salario_medio    133339 non-null  float64
dtypes: float64(2), int64(2), object(8)
memory usage: 13.2+ MB

In [102]:
df_limpo = df_limpo.assign(adimissao = df_limpo['adimissao'].astype('int64'))
df_limpo.info()
df_limpo

<class 'pandas.core.frame.DataFrame'>
Index: 133339 entries, 0 to 133348
Data columns (total 12 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   adimissao        133339 non-null  int64
 1   experiencia      133339 non-null  object
 2   contrato         133339 non-null  object
 3   cargo            133339 non-null  object
 4   salario          133339 non-null  int64
 5   moeda            133339 non-null  object
 6   usd              133339 non-null  int64
 7   residencia       133339 non-null  object
 8   remoto           133339 non-null  object
 9   empresa          133339 non-null  object
 10  tamanho_empresa  133339 non-null  object
 11  salario_medio    133339 non-null  float64
dtypes: float64(1), int64(3), object(8)
memory usage: 13.2+ MB

,adimissao,experiencia,contrato,cargo,salario,moeda,usd,residencia,remoto,empresa,tamanho_empresa,salario_medio
0,2025,Sênior,Tempo Integral,Solutions Engineer,214000,USD,214000,US,Remoto,US,Médio,172850.003845
1,2025,Sênior,Tempo Integral,Solutions Engineer,136000,USD,136000,US,Remoto,US,Médio,172850.003845
2,2025,Pleno,Tempo Integral,Engenheiro de Dados,158800,USD,158800,AU,Presencial,AU,Médio,143041.323489
3,2025,Pleno,Tempo Integral,Engenheiro de Dados,139200,USD,139200,AU,Presencial,AU,Médio,143041.323489
4,2025,Júnior,Tempo Integral,Engenheiro de Dados,90000,USD,90000,US,Presencial,US,Médio,99039.040264
...,...,...,...,...,...,...,...,...,...,...,...,...
133344,2020,Sênior,Tempo Integral,Cientista de Dados,412000,USD,412000,US,Remoto,US,Grande,172850.003845
133345,2021,Pleno,Tempo Integral,Principal Data Scientist,151000,USD,151000,US,Remoto,US,Grande,143041.323489
133346,2020,Júnior,Tempo Integral,Cientista de Dados,105000,USD,105000,US,Remoto,US,Pequeno,99039.040264
133347,2020,Júnior,Por Contrato,Business Data Analyst,100000,USD,100000,US,Remoto,US,Grande,99039.040264
133348,2021,Sênior,Tempo Integral,Cientista de Dados,7000000,INR,94665,IN,Híbrido,IN,Grande,172850.003845